### ISSUE TITLE
Cannot execute query without fetching all rows

### ISSUE THREAD

**Issue by jaceksan** [vertica/vertica-python#140]
**Use Case:**
Tool executing TPCH queries using multi-threading + advanced measuring / monitoring.
There are TPCH queries returning very large result set.
Worst-case is query #10 - circa 4M rows in case of 100GB TPCH size, 1230s duration, 1200s fetch time!

**Requirement:**
I would appreciate any change enabling execute without fetch, either by new argument or by design - 
without explicit call of e.g. fetchmany, it would only execute query, but it would throw away messages from backend.
cur.execute contains call of flush_to_query_ready() method in the beginning.
Even when I omit call of fetch, when I execute next TPCH query, it reads backend messages from execution of previous query - 
**this seems to me like even a bug, what do you mean?**

Btw I tested jaydebeapi + Vertica JDBC driver.
Although performance of fetch in this solution is extremely poor, when I use only execute without fetch, it works correctly, next executed query is not affected by previously not fetched result.

**Comment by jaceksan** [comment]
Is anyone able to at least answer my request (e.g. send me to hell)?

**Comment by alexjikim** [comment]
Sorry for the slow response.

This behavior has to do with combination of how the library is currently handling data streaming and transactions. The current execute() method finishes handling all messages to possibly send a commit execution at the end of a transaction (as opposed to creating a new socket for each execute).

There might also be a way to cancel the execution and only have to read the buffered data in the socket and not the entire result set, but id have to dig further into this.

in the mean time, a workaround would be to simply get a new cursor:
connection.reset_connection()
connection.get_cursor()

we could also provide a convenience method in cursor (cursor.reset() or something similar). let me know if you think that would be helpful.

**Comment by jaceksan** [comment]
Hi @alexjikim,
thanks for your answer!
I implemented the suggested workaround and it works well.

However, there are use cases, when resetting cursor is not possible, for example when LOCAL TEMPORARY tables are used.
We need to drop rows without loosing session/transaction state.
Let me know, if you can implement any method, which would keep session/transaction state.

**Comment by jaceksan** [comment]
@alexjikim Could you answer my question, please? 
Even simple NO would be appreciated, we need to know, if we have to focus on searching different kind of solution.....

**Comment by alexjikim** [comment]
hey @jaceksan, i no longer have write access to this repository and therefore will likely not be making more changes going forward.

When i looked at this, it wasnt clear to me how this could be accomplished given vertica's "simple" protocol (which is what this library uses). Its my understanding that theres a more advanced protocol, so it may be possible using that, but my knowledge of that protocol is basically zero.

**Comment by sitingren** [comment]
The backend would always send back all query results, no matter you call fetch or not. This is how Vertica's protocol works. All drivers have to handle these backend messages, including JDBC. It is likely that JDBC driver hide the problem, so you saw the performance of next executed query is not affected. So it is impossible to enable execute without fetch from client side.
