### ISSUE TITLE
vertica-python does not support SHA512 passwords

### ISSUE THREAD

**Issue by bradleyhurley** [vertica/vertica-python#147]
Here is the error message that is returned:
```
Message: b'The sending password for "<<user-name>>", encryption algorithm 
MD5 does not match the effective server configured encryption algorithm SHA512'
```

**Comment by alexjikim** [comment]
@tudit any chance you could help with this.

it seems the Authentication message value of 5 is used for both md5 and sha512 hash methods. I tried using a similar hash method to the current md5 implementation using hashlib.sha512() and 'sha512' as the prefix, but couldnt get it working. do you have any insight into what vertica is expecting?

**Comment by binglin1** [comment]
Hi, I've come across the same issue as bradleyhurley did. Has anyone, @bradleyhurley @alexjikim , find a solution yet?

**Comment by bradleyhurley** [comment]
Not a solution, but a work around. Change the users security algorithm.

https://my.vertica.com/docs/8.1.x/HTML/index.htm#Authoring/SQLReferenceManual/Statements/ALTERUSER.htm

I hope to actually dig into this issue this weekend.

**Comment by pankajs99** [comment]
Check the latest commit, this is all set!

https://github.com/vertica/vertica-python/pull/266
https://github.com/vertica/vertica-python/tree/d2a0e3e9bfb011417646e3d40a8b4ed0f28148e9
