### ISSUE TITLE
Errors not reported on subsequent failed loads

### ISSUE THREAD

**Issue by alan-delrio** [vertica/vertica-python#154]
Hi All,
The specific scenario that I'm reporting is when executing a COPY statement that fails, reusing the connection and executing a subsequent COPY command. 

The subsequent COPY command it not detected as failed, not exception is thrown and the client even claims to have received a Rows loaded count from Vertica. The copy command registered in the table QUERY_REQUESTS is marked as successful :False

I was able to reproduce the outcome using vertica-python but not vsql, the latter seems to always detect the error on subsequent copy commands, I think not detecting the failure on the subsequent copy command is related to the python client. Initially I thought it was Vertica but vsql always detect the failure

Note: The COPY command used to load data to Vertica was run using the method execute()  (copy() was not used at all)

**Comment by alexjikim** [comment]
i wasnt able to reproduce this. could you post a simple example that reproduces this?

also can you make sure you are setting REJECTMAX i the copy command? it doesnt sounds like this is your issue, since you are saying the first statement failed.. but just in case.

**Comment by mi-volodin** [comment]
I have a similar issue. The general example is as follows

```
with vertica_python.connect(**conn_info) as connection:
    curs = connection.cursor();
    curs.execute('select 1; Select * from asdasd.dsdsadasd;')
```

Of course, there is no such scheme or table on the second statement.

**Comment by mi-volodin** [comment]
I think the error is in `cursor` module. And it is connected with message processing.

Here's the example again
```
with vertica_python.connect(**conn_info) as connection:
    curs = connection.cursor();
    res = curs.execute('select 1;select 1; Select * from ddd.dasd;')
    print(curs.connection.read_message())
    print(curs.connection.read_message())
    print(curs.connection.read_message())
    print(curs.connection.read_message())
    print(curs.connection.read_message())
```

Which produce:
```
<vertica_python.vertica.messages.backend_messages.command_complete.CommandComplete object at 0x7f0fd6555080>
<vertica_python.vertica.messages.backend_messages.row_description.RowDescription object at 0x7f0fd6555080>
<vertica_python.vertica.messages.backend_messages.data_row.DataRow object at 0x7f0fd6555080>
<vertica_python.vertica.messages.backend_messages.command_complete.CommandComplete object at 0x7f0fd6555080>
<vertica_python.vertica.messages.backend_messages.error_response.ErrorResponse object at 0x7f0fd6555080>

```
so the Error message goes next after DataRow.

And that is processing block:
```
 # read messages until we hit an Error, DataRow or ReadyForQuery
        self._message = self.connection.read_message()
        while True:
            if isinstance(self._message, messages.ErrorResponse):
                raise errors.QueryError.from_error_response(self._message, operation)
            elif isinstance(self._message, messages.RowDescription):
                self.description = [Column(fd, self.unicode_error) for fd in self._message.fields]
            elif isinstance(self._message, messages.DataRow):
                break
            elif isinstance(self._message, messages.ReadyForQuery):
                break
            elif isinstance(self._message, messages.CommandComplete):
                break
            else:
self.connection.process_message(self._message)
```

From which it is clear that vertica_python reads from socket until either `CommandComplete`, `DataRow` or `ReadyForQuery` (not `Error` in current case) is processed.

I guess in my case I get description, then DataRow and that breaks the cycle.

I can try to make a PR to fix that. My suggestion is that we should stop only if we have `ReadyForQuery` status or `Error`. Until that - message reading should continue.

**Comment by mi-volodin** [comment]
I'm going to use this decision graph:

![default](https://user-images.githubusercontent.com/8374532/32786662-a0daa454-c965-11e7-84e6-f62ef7572396.png)

Does anyone knows if it is correct?
@alexjikim  maybe few comments?

**Comment by mi-volodin** [comment]
Yeah... that is not so obvious. But at least if I have several consequent DDLs - the `pass` in CommandComplete case might help. But for any statement like I had in example (which is with `SELECT` with nonzero row return) - the errors are skipped because of further `iterate()` process.

**Comment by mi-volodin** [comment]
Here's also a workaround for multiple statements with no expected output (FYI @alan-delrio )

```python
with vertica_python.connect(**conn_info) as connection:
    curs = connection.cursor();
    curs.execute('select 1; select 1; truncate table test;')
    
    while curs.nextset() is not None:
        pass
```
Should fail with `Error` (unless you have this table `test` somewhere).

Note that it ignores `DataRow` even if there is one.
If you expect the ouput the processing could be something like that:
```python
while True:
    for r in cur.iterate():
        # process rows
        pass
    if curs.nextset() is not None:
        break
```

**Comment by mickeynn** [comment]
Hi!
I have the same issue :) 
Test case:
 ```
CREATE TABLE test.test
(
    date_time TIMESTAMP NOT NULL CONSTRAINT C_PRIMARY PRIMARY KEY ENABLED
);

cursor.execute("INSERT INTO test.test (date_time) VALUES ('2017-11-17 01:00:00')")
```
Raw response from Vertica:
```
client_localeen_US@collation=binary
client_labelvertica-python-0.7.3-005ad354-cba5-11e7-8211-9801a7a64d8d
server_versionv8.1.1-8
long_string_typeson
protocol_version196608
standard_conforming_stringson
$S?

I
OUTPUT
standard_conforming_stringson
MARSoff
client_localeen_US@collation=binary
1
SERRORC23505MDuplicate key values: 'date_time=2017-11-17 01:00:00' -- violates constraint 'test.test.C_PRIMARY'F/scratch_a/release/svrtar29533/vbuild/vertica/Session/ConstraintEnforcement.cppL1476RemitConstraintValidationError
T
COMMIT
```
After read_message():
```
<class 'vertica_python.vertica.messages.backend_messages.authentication.Authentication'>
<class 'vertica_python.vertica.messages.backend_messages.authentication.Authentication'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.backend_key_data.BackendKeyData'>
<class 'vertica_python.vertica.messages.backend_messages.ready_for_query.ReadyForQuery'>
<class 'vertica_python.vertica.messages.backend_messages.row_description.RowDescription'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.parameter_status.ParameterStatus'>
<class 'vertica_python.vertica.messages.backend_messages.data_row.DataRow'>
<class 'vertica_python.vertica.messages.backend_messages.error_response.ErrorResponse'>
<class 'vertica_python.vertica.messages.backend_messages.ready_for_query.ReadyForQuery'>
<class 'vertica_python.vertica.messages.backend_messages.command_complete.CommandComplete'>
```
As we can see `ErrorResponse` goes after `ReadyForQuery`...

**Comment by mi-volodin** [comment]
@mickeynn Hi!

> As we can see ErrorResponse goes after ReadyForQuery...

First `ReadyForQuery` is from `connect` operation (maybe), because first cursor insert works also after it (see `RowDescription` and `DataRow` from first insert).
The interesting thing is... where the "second" ReadyForQuery? When second `execute` happens - it should "fast forward" to `ReadyForQuery` message first (or till empty queue). And then execute the second command. 

Are you sure this is the full message list?

**Comment by mickeynn** [comment]
эх... придется значит на ODBC переписывать :)

**Comment by mi-volodin** [comment]
@mickeynn ну не обязательно, я ж выложил workaround :) Он вполне работает, хотя и получился слегка низкоуровневый. Но для случаев, когда особо читать ничего не надо - он отлично подходит.

Кстати, из наших опытов (в компании), многие вещи гораздо быстрее работают через vsql+subprocess. Особенно чтение из базы, потому что не происходит создания python объектов. Если интересно - могу рассказать о нашем опыте.

**Comment by bcollazo** [comment]
I have a similar issue. I have a long SQL Script of CREATE TABLE commands, that if one fails, .execute doesn't raise any concerns (a.k.a. fails silently). If I execute the script from DBeaver its able to catch the error. vsql also alerts me on the error.

I've worked around for now doing something like:
```
commands = my_sql_script.split(';')
for command in commands:
        cur.execute(command)
```
So that each command is executed separately and thus raise error in case of any.

**Comment by Dschoni** [comment]
@bcollazo this will not help in the case of a silent fail in one single execute statement e.g. as a result of a constraint violation (see my linked example).

**Comment by alan-delrio** [comment]
We addressed the issue like this. We noticed not all messages are evaluated
u.flush_vertica_errors(cursor)
    def flush_vertica_errors(self,curs):
        if(curs._message is None
           or isinstance(curs._message, vmes.ReadyForQuery)):
            return

        message=curs._message

        while True:
            if isinstance(message, vmes.ErrorResponse):
                raise verr.ConnectionError(message.error_message())
            elif isinstance(message, vmes.ReadyForQuery):
                curs.connection.transaction_status = message.transaction_status
                curs._message = message
                break
            message = curs.connection.read_message()
       or isinstance(curs._message, vmes.ReadyForQuery)):
        return

**Comment by sitingren** [comment]
This topic has been added into README: [Send Queries and Retrieve Results](https://github.com/vertica/vertica-python#send-queries-and-retrieve-results)
In short, the easiest way to evaluate all protocol messages is to call `fetchall()` and `nextset()`.
