### ISSUE TITLE
How can to make upload exception while loading csv file to Vertica?

### ISSUE THREAD

**Issue by drno-reg** [vertica/vertica-python#170]
Hello,

at current moment time I load csv file to Vertica using this script

connection = vertica_python.connect(**conn_info)
cursor = connection.cursor()
with open("C:\\DataBases\\csv\\%s_%s.csv" % (FILE_NAME, TABLE_NAME), "rb") as fs:
    my_file = fs.read()
cursor.copy("COPY %s.%s from stdin PARSER fcsvparser(type='traditional', delimiter=';', record_terminator='\n',)" %(SCHEMA_NAME, TABLE_NAME), my_file)
connection.commit()
connection.close()

BUT this variant Does not show exceptions.

I want to upload execptions into File, but I run this script not on vertica server, on my local server.

How to solve this problem?

**Comment by alexjikim** [comment]
i believe this has to do with vertica's default handling of copy errors (ignore them). Try setting REJECTMAX to 1 (or whatever threshold you want the copy command to error out on).

https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/SQLReferenceManual/Statements/COPY/COPY.htm

**Comment by sitingren** [comment]
No conversations for a long time. Closed. 

Reopen this issue if you still have questions.
