### ISSUE TITLE
Inserts with timestamp parameters raise error

### ISSUE THREAD

**Issue by dlipowitz** [vertica/vertica-python#175]
https://github.com/uber/vertica-python/blob/37e6b9cd33a2eec905f2b4b1f00e4cc004aff383/vertica_python/vertica/cursor.py#L348

Line 348 is adding timestamp bind parameters to my INSERT statement's VALUES clause without surrounding quotes.

e.g. ```INSERT INTO some_table (some_timestamp) VALUES (2016-05-27 16:52:55.658182)```

should become

```INSERT INTO some_table (some_timestamp) VALUES ('2016-05-27 16:52:55.658182')```

**Comment by darwinyip** [comment]
Will this get addressed? Getting the same issue.
