### ISSUE TITLE
Python3 vertica-python literal connection arguments issue

### ISSUE THREAD

**Issue by dangosludge** [vertica/vertica-python#176]
Running Python3 with literal connection arguments generates errors trying to connect.  If 'some_literal' is used as a literal connection argument, then connection.py chokes trying to convert to bytes in method write's sendall(message.to_bytes()), and to add insult to injury the exception handling fails because the thrown <class 'struct.error'>  value of """error("argument for 's' must be a bytes object",)""" does not possess a message attribute: AttributeError: 'error' object has no attribute 'message'.  If one then tries to use a bytes literal connection argument such as b'some_literal', then connection.py chokes trying to encode it as ascii, "AttributeError: 'bytes' object has no attribute 'encode'".  Have had no issues using vertica-python with Python 2.x but finally moving to 3.x and can't even connect, nice.

**Comment by DerrickRice** [comment]
AttributeError: 'error' object has no attribute 'message' is from #309
