### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by JettJengaGod** [vertica/vertica-python#180]
Whenever I try to connect to my vertica DB, I get this connection error. I'm sure that it is authenticating as invalid credentials get rejected with a auth error. Any advise on how to proceed with fixing this?
````
Traceback (most recent call last):
  File "uber.py", line 5, in <module>
    connection = vertica_python.connect(**con_info)
  File "/usr/local/lib/python2.7/dist-packages/vertica_python/vertica/connection.py", line 25, in connect
    return Connection(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vertica_python/vertica/connection.py", line 45, in __init__
    self.startup_connection()
  File "/usr/local/lib/python2.7/dist-packages/vertica_python/vertica/connection.py", line 271, in startup_connection
    'salt': getattr(message, 'salt', None)}))
  File "/usr/local/lib/python2.7/dist-packages/vertica_python/vertica/connection.py", line 180, in write
    raise_from(errors.ConnectionError, e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
vertica_python.errors.ConnectionError


#CODE:
import vertica_python
# Fake DB info
con_info = {'host' : '1.1.1.1', 'port' : 5433, 'user' : 'username', 'password' : 'pass', 'database' : 'db', 'read_timeout' : 6000}

connection = vertica_python.connect(**con_info)
connection.close()

**Comment by AndrewJudson** [comment]
@JettJengaGod does your Vertica server require SSL? Your con_info doesn't include an SSLContext, so if your server requires it that could be a cause of the connection failure.

**Comment by JettJengaGod** [comment]
@AndrewJudson It does not require SSL.

**Comment by AndrewJudson** [comment]
@JettJengaGod you could print out the different fields for message here? https://github.com/uber/vertica-python/blob/master/vertica_python/vertica/connection.py#L269
Could shine some light on what is going on. Are you using the latest version?

**Comment by JettJengaGod** [comment]
@AndrewJudson I am using version 0.7.3 

When I look into that, it looks like I am getting
````
{ValueError} unsupported authentication method: 11

**Comment by hc000** [comment]
@AndrewJudson I think its because the password contains non alpha numeric characters.

**Comment by JettJengaGod** [comment]
@AndrewJudson @hc000 non alpha numeric characters seemed to be the issue. Thanks.

**Comment by JettJengaGod** [comment]
Do you support schemas or tables with the '_' character in it?

**Comment by sitingren** [comment]
@JettJengaGod 
`{ValueError} unsupported authentication method: 11` means your password will expire soon. This should be a warning, but currently it is an exception so you connection fails, we should fix that. Try to connect to your database after changing the password to see if it works.

**Comment by Akhilj786** [comment]
> Do you support schemas or tables with the '_' character in it?

@AndrewJudson Yes they do support `_` in schema name.
