### ISSUE TITLE
decimal.Decimal is returned instead of floats

### ISSUE THREAD

**Issue by chanansh** [vertica/vertica-python#189]
I have a table with a column of type Numeric but once I fetch_many I get in python the type as decimal.Decimal (e.g. 0E-15 instead of 0).

**Comment by bradleyhurley** [comment]
Can you provide a sample create table / insert statement to recreate this issue?  If I can recreate the issue I can attempt to open a PR with a fix.

**Comment by chanansh** [comment]
Please close. The vertical was of type NUMERIC

**Comment by sitingren** [comment]
Works as expected, not a bug.
