### ISSUE TITLE
Query using named parameters - how to debug formatting?

### ISSUE THREAD

**Issue by chanansh** [vertica/vertica-python#193]
How can I get the query string before it sent to the driver and after parameters replacement? I would like to debug and cannot...

**Comment by bradleyhurley** [comment]
@chanansh You can add a print statement above the following line:
https://github.com/uber/vertica-python/blob/d6a6d5213d6442ae5330ec9dfdff78b9e1cd2c43/vertica_python/vertica/cursor.py#L131

`print(operation)`

If you're interested I can open a PR with a debug/verbose flag on the connection.

@alexjikim  - Is this project still being maintained?  I notice you said awhile back that you no longer have write permissions.

**Comment by sitingren** [comment]
This issue has not had recent activity. Closed. Please reopen if anyone has further questions.

We would consider add messages about query strings to logging.

**Comment by AdityaRon** [comment]
I have the same issue. I need to be able to see the query with parameter substitution. Tried printing cursor.operation which gives the query before substitution.

**Comment by bradleyhurley** [comment]
@AdityaRon - I don’t actually use Vertica anymore, but if I have some free time I will download the community edition and open a PR. In my use case we did all of the SQL variable substitution outside of vertica-python and used Jinja. With the Jinja approach the sql string you pass vertica-python is ready to be executed.

**Comment by sitingren** [comment]
@AdityaRon For `Cursor.execute()`, you can set log level to `INFO` or greater to see the query with parameter substitution in log file. `Cursor.executemany()` does not do parameter substitution at client side so this cannot be applied.

It is recommended to use prepared statement if you are using SQL variable substitution, which is a safer option. Please see `Query using server-side prepared statements` section in README.md

**Comment by AdityaRon** [comment]
@sitingren  Appreciate the quick response. It worked! I didn't have to use server-side statement though. Infact it didnt work with server side statement, It was just printing the bind parameters. I used client side statement and set the logging level to info and boom it printed the prepared statement in the log!
