### ISSUE TITLE
Errors are not reported when multiple statements are executed in a query

### ISSUE THREAD

**Issue by SunilNekkanti** [vertica/vertica-python#197]
When cursor.execute is passed a query that has multiple statements, (delimited by semicolon) and one of the statements results in a database error, that error is not raised (unless it is the first statement).

Here's an example of a query that when run on its own raises a MissingColumn exception:

import vertica_python

params = get_default_db_params()
connection = vertica_python.connect(**params)
cursor = connection.cursor()
cursor.execute('select a;')  # bad query to raise and exception
When this query is among multiple statements (and not the first statement) no error is raised.

cursor.execute('select 1; select a;')
The expected results is a MissingColumn exception.

Tested with vertica_python 0.7.3 on Python 3.5.0, with Vertica 9.0.x db.

This was an issue(#124 ) that has been closed but this issue still exists in the latest vertica_python 0.7.3

**Comment by nchammas** [comment]
I think this is a dup of #185.

**Comment by sitingren** [comment]
This works as expected. See https://github.com/vertica/vertica-python/issues/124#issuecomment-301279343. vertica-python streams data results, so you have to iterate through results with `nextset()` to get the MissingColumn exception.

**Comment by hannahshachar** [comment]
I have the opposite problem, I have a statement that drops the table if it exists and then creates the table again with a long query.  As soon as it Drops the table, it moves on in the python to the next part, not waiting for the second query to complete.  Is it the same solution?

**Comment by sitingren** [comment]
> I have the opposite problem, I have a statement that drops the table if it exists and then creates the table again with a long query. As soon as it Drops the table, it moves on in the python to the next part, not waiting for the second query to complete. Is it the same solution?

@hannahshachar Based on your description I think the answer is yes. Please read up to the README, especially the `nextset()` section: https://github.com/vertica/vertica-python#nextset
