### ISSUE TITLE
select queries returning newstr b''

### ISSUE THREAD

**Issue by naterodata** [vertica/vertica-python#204]
I'm running python 2.7.14 and it looks like queries have begun returning newstr byte literals (b'xxx') instead of normal u'xxx' strings.  Any ideas on how to change it/force it back?  This occurred when I upgraded/installed a different python package.

**Comment by sitingren** [comment]
I'm not familiar with the original design, but looking at the commit history, this behavior change has happened for a long time (since version 0.6.0, Apr 28 2016). Calling `unicode()` can simply transfer it back to u'xxx' string.
