### ISSUE TITLE
Returned vertica error codes?

### ISSUE THREAD

**Issue by craigsoules** [vertica/vertica-python#210]
Hello,

Is there a way to retrieve the actual error code returned by Vertica from the raised Exception?  It looks from the code like you're parsing the returned messages, but I can't seem to figure out if any part of that is the actual error code, and it's tricky to simply test since I don't really want to force the database into recovery for testing purposes ;-)

Thanks!
Craig

**Comment by sitingren** [comment]
Hi @craigsoules

**Comment by sitingren** [comment]
Hi @craigsoules

**Comment by sitingren** [comment]
Hi @craigsoules , Vertica server does support retrieving the error code, but this feature requires the protocol version the client uses to communicate with the server to be at least 3.4. Unfortunately, protocol version 3.0 is implemented in this [library](https://github.com/vertica/vertica-python/blob/master/vertica_python/__init__.py#L63) by now. It is not a trivial work if we want to upgrade the protocol version.

**Comment by sitingren** [comment]
The protocol version is upgraded to 3.4 in commit [5be9fc94a7](https://github.com/vertica/vertica-python/commit/5be9fc94a7894bac179a628bc16223ace727f6ee). Now you can see "Error Code" from the raised Exception.
