### ISSUE TITLE
Bug in executemany when trying to insert NULL value into a column defined as an INT

### ISSUE THREAD

**Issue by omatveyuk** [vertica/vertica-python#211]
There seems to be a bug in the executemany function when trying to insert NULL value into column defined as an INT.
For example, if i have a table with 3 columns (col A: int, col B:string, col C: double) and I am trying to insert 'NULL,"Hello World",2,35' using COPY FROM, the executemany throws an exception.
When I try to omit NULL and use the empty string instead of the NULL, (Example: ',"Hello World",2,35'), the code works.

**Comment by Dschoni** [comment]
I'm not sure if I understand your example right, but in both cases there seem to be several issues with your query to start with.  `2,35` is not standard notation for a double in python, this should be `2.35`.  As far as I am aware, there is no mapping from `NULL` to anything. I can only speak from the psycopg2 side of this problem, but for this mapping an empty string or the python `None` object is usually used.

**Comment by sitingren** [comment]
I believe this issue is a duplicate of #181.
