### ISSUE TITLE
Create repos for vertica sqlalchemy and alembic dialects

### ISSUE THREAD

**Issue by darwinyip** [vertica/vertica-python#235]
Is it possible to create official support repos for sqlalchemy and alembic?

There is one for sqlalchemy but would be nice to have one with official support from Vertica.
https://github.com/LocusEnergy/sqlalchemy-vertica-python

**Comment by sitingren** [comment]
That's a great idea. However, we have many other high priority features/issues we would like to address first. So, unfortunately, we don't have engineering cycles to make it in the near feature releases. Thank you for your interest, we'll publish any update here.

**Comment by karhohs** [comment]
@sitingren do you accept pull requests? The https://github.com/LocusEnergy/sqlalchemy-vertica-python has proved very useful and it would be great to add this kind of sqlalchemy support to the official python vertica project.

**Comment by lemeryfertitta** [comment]
@sitingren @darwinyip I've been maintaining https://github.com/LocusEnergy/sqlalchemy-vertica-python for the last few years, and we'd be happy to pass it off to Vertica if they are interested.

@karhohs In the meantime, I'm happy to continue to accept pull requests.

**Comment by sitingren** [comment]
@lemeryfertitta Thank you for maintaining this great repo and making Vertica better! 

@karhohs Currently, we don't have enough engineering resource to support sqlalchemy and accept pull requests. Even if we take over https://github.com/LocusEnergy/sqlalchemy-vertica-python, we may not have so much contribution.

**Comment by tomwall** [comment]
As Siting said, we'd love to see better python ORM support. But for now our priority is to implement the major missing pieces of the python client. Some of those, like server-side prepared statements, should have a very positive impact on the experience in those sort of tools. Once we fill in those gaps we will likely turn our attention to the popular higher level projects that build upon vertica-python.

For SQLAlchemy in particular, it's not clear that the dialect should be a part of this project. In theory the same dialect should be able to support things like pyodbc + vertica odbc too, and we'd like to see it target the widest range of users possible.
