### ISSUE TITLE
Messages are being printed to console via a print statement since v0.8.1

### ISSUE THREAD

**Issue by mikeengland** [vertica/vertica-python#251]
In the commit https://github.com/vertica/vertica-python/commit/feb7869c65f5bbaaa0033557c847e58e55b58c08#diff-08e1a2fc0457d9f1c5a22e5344108fa4R470 (new line 470), the code executes a print statement if there is a message.

Please can this be changed to either a Python warning or a log message so it can easily be ignored when using vertica-python as a third party module?

**Comment by sitingren** [comment]
Thank you for your feedback! We have an open issue #243 to gather ideas about message handling. Please leave your suggestions there. It would be great if you also describe your expectation about message handling behaviors when using vertica-python as a third party module.

For now, if you feel it is annoying, feel free to comment out that print statement in your installed package.
