### ISSUE TITLE
Is there any way to get the count of copied rows after a COPY statement (using cursor.copy) .

### ISSUE THREAD

**Issue by Vicolatope** [vertica/vertica-python#256]
Hello,
first of all, thank you for this module which works perfectly for me !
I just couldn't figure out any way to get the count of inserted rows after a COPY statement.
Is there any way to get this number ? Thank you !!!

**Comment by sitingren** [comment]
Query `select get_num_accepted_rows();` is one way to get the count of inserted rows. See [Vertica Documentation](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/BulkLoadCOPY/MonitoringCopyLoadsMetrics.htm?tocpath=Administrator's%20Guide%7CBulk-Loading%20Data%7C_____13). Looking at the implementation of `cursor.copy()`, I'm not sure how to retrieve the count number from the client. I'll check the protocol and give you updates later.

**Comment by Vicolatope** [comment]
Thank you for your quick response ! For my use, this query seems to do the job very well ! Thank you for your work

**Comment by sitingren** [comment]
@Vicolatope I'm glad this workaround works for you!

Here is what I find after investigations: In a regular `COPY from files` (e.g. `cursor.execute("copy copytests_1 from '/path/to/data'")`), you should get the accepted row count with `cursor.fetch*()`. The problem you encounter (maybe only in a `COPY from STDIN`) is a limitation imposed by the server. It is tricky for the server to return accepted row count in this situation. At present, I don't see our engineering team have a plan to fix this server-side problem in the near future, so I would recommend you keep using this query `select get_num_accepted_rows();`. Thanks!
