### ISSUE TITLE
[Question] What is the difference between the SDK and this repo?

### ISSUE THREAD

**Issue by darwinyip** [vertica/vertica-python#267]
What is the difference between this repo and https://www.vertica.com/docs/9.2.x/HTML/PythonSDK/index.html ?

**Comment by sitingren** [comment]
Python SDK is one of [User-Defined Extensions (UDxs)](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/ExtendingVertica/UDx/DevelopingUDxs.htm?tocpath=Extending%20Vertica%7CDeveloping%20User-Defined%20Extensions%20(UDxs)%7C_____0) Vertica provides. Please see [the Vertica documentation](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/ExtendingVertica/Python/IntroductionPythonSDK.htm?tocpath=Extending%20Vertica%7CDeveloping%20User-Defined%20Extensions%20(UDxs)%7CDeveloping%20with%20the%20Python%20SDK%7C_____0) to learn more about Python UDx SDK.

Here are some good [examples](https://github.com/vertica/UDx-Examples/tree/master/Python) of using Python SDK. Basically, for example, if you want to run a sql with customized function like `SELETE add3ints(num1, num2, num3) AS add3ints_sum FROM tbl;`, you can define `add3ints(arg1, arg2, arg3)` function in Python with Python SDK.
