### ISSUE TITLE
Add an example on how to enable the package to use SHA512 auth

### ISSUE THREAD

**Issue by ruojol** [vertica/vertica-python#269]
Add an example of conn_info dict on SHA512 key support. Doing the connection via the example 
`conn_info = {'host': '127.0.0.1',
             'port': 5433,
             'user': 'some_user',
             'password': 'some_password',
             'database': 'a_database',
             # autogenerated session label by default,
             'session_label': 'some_label',
             # 10 minutes timeout on queries
             'read_timeout': 600,
             # default throw error on invalid UTF-8 results
             'unicode_error': 'strict',
             # SSL is disabled by default
             'ssl': False,
             # using server-side prepared statements is disabled by default
             'use_prepared_statements': False,
             # connection timeout is not enabled by default
             'connection_timeout': 5}
`
Results in 
` encryption algorithm MD5 does not match the effective server configured encryption algorithm SHA512', Sqlstate: b'VX001', Routine: b'password_verify', File: b'/scratch_a/release/svrtar28000/vbuild/vertica/Basics/ClientAuthentication.cpp', Line: b'536', Error Code: b'6429'`

Since there propably is something missing from the conn_dict.

**Comment by sitingren** [comment]
@ruojol Please note the SHA512 support is currently on master branch, not in any release. It will go into next release very soon. Thanks.

**Comment by sitingren** [comment]
See discussion in #266.

Also, there is a [test](https://github.com/vertica/vertica-python/blob/c5668404b73dd19909d93279e9993d64025cd1a6/vertica_python/tests/integration_tests/test_authentication.py#L31) for SHA512, please take a look if you are interested.
