### ISSUE TITLE
"THROW_ERROR" function does not throw error in vertica_python using python3

### ISSUE THREAD

**Issue by alecsaunders** [vertica/vertica-python#272]
The Vertica [Error-Handling Function](https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Error-handling/THROW_ERROR.htm) `THROW_ERROR` does not in fact throw an error on execution when using vertica_python using python3.

Python Version: 3.7.2
Vertica-python version: 0.9.1

When I execute the sql containing the THROW_ERROR function python does NOT throw an error.

```python
cur.execute("SELECT THROW_ERROR('test error')")
```

It is only when `fetchall()` or `fetchone()` is called that an error is thrown.

I have tested this issue by simply calling the function (as shown above) and when using the function inside a case statement:

```python
cur.execute("SELECT CASE WHEN COUNT(*) = 10 THEN 'SUCSESS!' ELSE THROW_ERROR('error') END FROM test;
```

The logic of my script does not require me to return any results with `fetchall()`. I would like `THROW_ERROR` to just throw an error on execution.

---

To provide some help in diagnosing this issue, I noticed that when `_execute_simple_query` is called in `cursor.py`, the instance type of `self._message` (row 479) is `RowDescription` and *not* `ErrorResponse` as it should be. I did some debugging and here is the `self._message`.

```
RowDescription: [{'name': 'THROW_ERROR', 'table_oid': 0, 'schema_name': None, 'table_name': None, 'attribute_number': 0, 'data_type_oid': 9, 'data_type_size': 65535, 'data_type_name': 'Varchar', 'null_ok': True, 'is_identity': False, 'type_modifier': 15, 'format_code': 0}]
```

**Comment by sitingren** [comment]
@alecsaunders Thanks for reporting. This is a similar issue of #255. Please read the explanation in #255.

Here are protocol messages that are sending(=>) and receiving(<=) during sql executions:
```
=> Query: SELECT THROW_ERROR('test error');
<= RowDescription: cursor.execute() returned at here
<= ErrorResponse
```
In vertica-python version 0.9.1, the logic of `cursor.execute()` makes the function stop reading remaining protocol messages if it receives a RowDescription message. For your specific problem, we can add error handling after receiving RowDescription messages. But in general, ErrorResponse messages can occur anytime in the protocol cycle of a query, only running `cursor.fetchall()` can you iterate through all remaining protocol messages and catch ErrorResponse.
