### ISSUE TITLE
Any way to export large dataset from python vertica

### ISSUE THREAD

**Issue by hixus** [vertica/vertica-python#275]
There seems to be copy from SDIN for reading large datasets but is there any fast way to read the results to client filesystem? Iterating cursor seems too slow if there are millions of rows.

**Comment by sitingren** [comment]
@hixus Here is what I know about vertica server and client:

1. There is no SQL statement in Vertica like `COPY table TO file` to write the content of a database table to an operating system file on the client machine.
2. vertica-python implements the [Python DB-API v2.0](https://www.python.org/dev/peps/pep-0249/#cursor-methods) protocol and does not add so many optional extensions. There is no cursor function that writes the content of a table to a python file-like object.

**Comment by sitingren** [comment]
If you want to improve the performance of exporting data by iterating cursor, here are something you can try:
1. Use [PyPy](https://pypy.org/) interpreter: some of our experiments shows PyPy has a better read performance than CPython interpreter. Switch your python interpreter and see if the export speeds up:
   - Install pypy on your machine.
   - Install vertica-python and its dependencies on pypy.
   - Replace `python your_program.py` with `pypy your_program.py`.
2. Use clients of other programming languages: The Python language limits vertica-python to do read/write-intensive jobs. The poor performance is a big drawback of client written in python compared to other clients. If using vertica-python is not required, try other vertica clients like JDBC, ODBC, vsql, etc.

**Comment by hixus** [comment]
Ok thanks. I'm working on Apache Airflow Vertica operator so thats why vertica-python would have been preferred. Decided to do queries in to a new table and after that wrapped vsql for exporting the data to a client.
