### ISSUE TITLE
cursor.executemany() implicitly commits the data

### ISSUE THREAD

**Issue by ivan-ponomarev** [vertica/vertica-python#292]
Calling `cursor.executemany()` commits the data if `use_prepared_statements` set to False even if you do `cursor.execute('ROLLBACK;')`.

I think it because it is implemented with `COPY` command but without `NO COMMIT` option.

I'm not sure this is expected behaviour.

**Comment by Dschoni** [comment]
AFAIK `autocommit=True` is standard in Vertica Connections.

**Comment by Dschoni** [comment]
See also https://github.com/vertica/vertica-python/issues/232

**Comment by ivan-ponomarev** [comment]
@Dschoni It happens even if I explicitly open transaction. Here is my sample script:
```python
import vertica_python

connection = vertica_python.connect(host='192.168.250.67', port=5433, user='dbadmin', password='', database='rudolph')
cursor = connection.cursor()

# Do some preparation
cursor.execute('CREATE TABLE IF NOT EXISTS my_test (col INT);')
cursor.execute('SET SESSION AUTOCOMMIT TO off;')

# Test transaction rollback
cursor.execute('BEGIN;')
cursor.executemany('INSERT INTO my_test (col) values (%s);', [[1], [2], [3]])  # This command expected to be rolled back
cursor.execute('ROLLBACK;')

count = cursor.execute('SELECT count(*) from my_test;').fetchone()[0]

if count:
    print('Test failed, data is actually commited despite of rollback')
else:
    print('Test passed, rollback works')
```

**Comment by Dschoni** [comment]
In this case, I am pretty sure the behaviour is unexpected and it should be fixed. Thanks for that self-contained minimal example.

**Comment by tomwall** [comment]
Yep, that's definitely a bug. When the statement is rewritten as COPY STDIN, it needs to be aware if autocommit is enabled and add NO COMMIT as needed to preserve INSERT semantics.

https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/cursor.py#L206
