### ISSUE TITLE
Issue setting DEFAULT_USER in AWS serverless environment

### ISSUE THREAD

**Issue by bryanherger** [vertica/vertica-python#296]
We're seeing an issue on AWS serverless scripts (Glue, Lambda) where DEFAULT_USER is set to the login user, but on AWS serverless there is no real user account associated, so the call fails:

```
File "/tmp/glue-python-scripts-51dayeq0/vertica_python_poc.py", line 1, in 
File "/glue/lib/installation/vertica_python-0.9.3-py3.6.egg/vertica_python/init.py", line 38, in 
from .vertica.connection import Connection, connect
File "/glue/lib/installation/vertica_python-0.9.3-py3.6.egg/vertica_python/vertica/connection.py", line 60, in 
DEFAULT_USER = getpass.getuser()
File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 10000'
```

Can you add error handling at "vertica/connection.py, line 60" to set the default to "dbadmin" if getpass.getuser() fails?

**Comment by bryanherger** [comment]
Context on Vertica Forum:  https://forum.vertica.com/discussion/240770/load-data-from-spark-dataframe-to-vertica-from-aws-glue#latest

**Comment by tomwall** [comment]
Thanks for the report. This is an interesting use case and the serverless security model clearly wasn't anticipated. 

I don't think it is appropriate to use dbadmin as a default user. dbadmin is not necessarily a valid user, and if it is, it is a very privileged user. If someone forgot to set a username in this environment and it defaulted to dbadmin, the dba would probably not appreciate a bunch of failed dbadmin login attempts in their request logs coming from this client.

That said, if loading the default user via getuser() fails, it should be allowed to proceed without a default. You can't avoid having to set a username manually in this scenario. Later on in the process, when we go to use the username, if it hasn't been set the connection should fail with a more obvious error, that the username wasn't set and couldn't be determined. That way the connection could fail before the socket is opened and you'd avoid a failed login attempt and all the potential server-side monitoring and auditing concerns that stem from it.

**Comment by sitingren** [comment]
The os login user is something client sends to server in Startup message. So `getpass.getuser()` was used when constructing the Startup message. Fixed now.
