### ISSUE TITLE
format_operations_with_parameters is not sql-injection-safe

### ISSUE THREAD

**Issue by DerrickRice** [vertica/vertica-python#303]
The example queries in documentation give the impression that the following is a reasonable way to construct queries:

```
cursor.execute("select name from table_of_stuff where column = %s", [user_input])
```
Upon code review, there are the following concerns:

1. `Cursor.format_operations_with_parameters` takes direction from the type of the input, rather than the specifier of the placeholder. Unclear if this is an issue, since the subsequent Python-native `%` operation may handle misaligned types by throwing an error. I believe the following will give an error "TypeError: %d format: a number is required, not str"

```
cursor.execute("select name from table_of_stuff where column = %d", ["foobar"])
```

2. More critically, if the type of the parameter is unknown or doesn't fall into one of the earlier two categories, format_operations_with_parameters uses `str(value)`, which would allow for non-string types to stringify to sql-injection-capable strings.

Instead, `format_operations_with_parameters` should take the **placeholder** as the indication of how to format the input, rather than the type of the input as the indication.

------------

Also, there is no existing format specifier for identifiers (a separate issue, I suppose). Attempting to construct SQL such as "CREATE TABLE %s..." fails, since %s will be single quoted, and it ought to be double quoted.

The library does not appear to provide a means of escaping an input as suitable for use as an identifier.

**Comment by sitingren** [comment]
This is one of the parameter style defined in DBAPI 2.0 (https://www.python.org/dev/peps/pep-0249/#paramstyle). Placeholders in the statement are represented by `%s`. It is not used for formatting string. `%d`,`%x`,`%f`,etc are not valid placeholders. Same as using server-side prepared statements, the placeholder cannot be placed anywhere in the query string, it should represent a value. It is expected that "CREATE TABLE ? ..."  and "CREATE TABLE %s ..." would fail. On the other side, as mentioned in readme, only server-side prepared statements prevents SQL injection attacks. We leave this %s parameter style for backward compatibility.

%-style string formatting is pretty old. `str.format` or f-Strings(Python 3.6+) is to be preferred over %-style formatting. So there'll be no problem if you use something like `cursor.execute("SELECT TABLE {} WHERE col = %s".format('tbl_name'), [user_input])`.
