### ISSUE TITLE
FIELD_DEFINITIONS for NoticeResponse (and others?) not compatible with Python3

### ISSUE THREAD

**Issue by DerrickRice** [vertica/vertica-python#309]
https://github.com/vertica/vertica-python/blob/b6d5dff4cb3f460ff6a479047c5365736db96d86/vertica_python/vertica/messages/backend_messages/notice_response.py#L46-L81

`FIELD_DEFINITIONS` has the field "name" as string literals. It is important for the field names found on the wire (i.e. in `data`) to match by name.

In Python3, those names would be strings, aka unicode, which are not equal to (`==`) the same values as bytes. The name pulled from `data` is bytes.

The result is that none of the desired attributes (i.e. `error.message`) are found on the object.

Fix is to have the field names in `FIELD_DEFINITIONS` be bytes (which may require using `six` for Python2.7 compat)

**Comment by DerrickRice** [comment]
## Reproducer
```python
from __future__ import print_function

import vertica_python

with vertica_python.connect() as connection:
    try:
        connection.cursor().execute('select 1 from doesnotexist;')
    except vertica_python.errors.QueryError as err:
        print("Error:\n\t{}".format(err.message))
```

## Python2.7 output
```
Error:
        Severity: ERROR, Message: Relation "doesnotexist" does not exist, Sqlstate: 42V01, Routine: throwRelationDoesNotExist, File: /scratch_b/drice/server/vertica/Catalog/CatalogLookup.cpp, Line: 3780, Error Code: 4566, SQL: u'select 1 from doesnotexist;'
```

## Python3 output
Paths redacted
```
Traceback (most recent call last):
  File "???/repro.py", line 7, in <module>
    connection.cursor().execute('select 1 from doesnotexist;')
  File "???/cursor.py", line 158, in execute
    self._execute_simple_query(operation)
  File "???/cursor.py", line 478, in _execute_simple_query
    raise errors.QueryError.from_error_response(self._message, query)
vertica_python.errors.MissingRelation: Severity: b'ERROR', Message: b'Relation "doesnotexist" does not exist', Sqlstate: b'42V01', Routine: b'throwRelationDoesNotExist', File: b'/scratch_b/drice/server/vertica/Catalog/CatalogLookup.cpp', Line: b'3780', Error Code: b'4566', SQL: 'select 1 from doesnotexist;'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "???/repro.py", line 9, in <module>
    print("Error:\n\t{}".format(err.message))
AttributeError: 'MissingRelation' object has no attribute 'message'
```

**Comment by sitingren** [comment]
The 'message' attribute was mark deprecated in 2.6 and was removed in Python3.
https://www.python.org/dev/peps/pep-0352/

 `str(err)` instead of `err.message` should do the trick.

**Comment by DerrickRice** [comment]
It looks like what I wanted was `err.error_message.foo` (whether `.message`, or `.error_code` or other) and it works in Python3.
