### ISSUE TITLE
ConnectionError raised with no explanation (raise_from)

### ISSUE THREAD

**Issue by DerrickRice** [vertica/vertica-python#314]
When a ConnectionError is raised by type, as is seen in the `raise_from(...)` usages below, it is created with no message. As a result, it's `str()` value is empty in Python3.

https://github.com/vertica/vertica-python/blob/b5f1e44f16f18ff476071be7aa05355fc9e913b5/vertica_python/vertica/connection.py#L432-L435

https://github.com/vertica/vertica-python/blob/b5f1e44f16f18ff476071be7aa05355fc9e913b5/vertica_python/vertica/connection.py#L543-L547

and perhaps more.

Recommendation: Change these to raise specific instances of `ConnectionError` with a reasonable message. At a minimum:

```
raise_from(ConnectionError(str(e)), e)
```

**Comment by sitingren** [comment]
Related issue: #288

@DerrickRice Yes, your recommendation makes sense.
