### ISSUE TITLE
sql injection hazard?

### ISSUE THREAD

**Issue by chanansh** [vertica/vertica-python#338]
Since the current code uses re.resub someone can pass a parameter which is actually an sql statement. 
Or maybe I am wrong?!
see https://realpython.com/prevent-python-sql-injection/

**Comment by sitingren** [comment]
Please read "Query using server-side prepared statements:" section in the [Readme](#README.md).

**Comment by sitingren** [comment]
You can get rid of sql injection by using "server-side prepared statements".
Please re-open this issue if you have further questions.

**Comment by andrewasheridan** [comment]
Question on this topic: What about Identifiers?

Currently there is no way (afaik) to specify that a variable is a schema or table name, so Vertical wraps them in 'quotes'. 

This means we have to use string formatting for these, or Jinja2 Template rendering, either of which could be less than safe. 

Note this doesn’t seem to be an issue in vsql

**Comment by sitingren** [comment]
@andrewasheridan Can you give me an example of using vsql with identifier arguments that prevent sql injection? AFAIK, "server-side prepared statements" doesn't handle sql identifiers. I'm not sure if vsql is just substitute variables (define with `\set`) into regular SQL statements, but in my experiment so far I can drop a table in a SELECT query.
