### ISSUE TITLE
Is it possible to get a cursor thanks to a DSN ? 

### ISSUE THREAD

**Issue by oualib** [vertica/vertica-python#339]
I just wonder if it is possible to create a cursor without entering implicitly the credentials, something like: conn(dsn = "VerticaDSN").cursor() ??

**Comment by sitingren** [comment]
What do you mean for “VerticaDSN”? Currently we support it to be a connection string:
`vertica_python.connect(dsn='vertica://(user):(password)@(host):(port)/(database)?(arg1=val1&arg2=val2&...)')`

Otherwise, you have to manually read credentials from environment variables or files.

**Comment by oualib** [comment]
Ah ok, because pyodbc provides a very simple way to connect without entering manually the credentials looking at your ODBC.ini. Is it on the roadmap otherwise I can code it?

**Comment by oualib** [comment]
I just did it in case:

```
def read_dsn(dsn: str):
	f = open(os.environ['ODBCINI'], "r")
	odbc = f.read()
	f.close()
	if ("[{}]".format(dsn) not in odbc):
		raise ValueError("The DSN '{}' doesn't exist".format(dsn))
	odbc = odbc.split("[{}]\n".format(dsn))[1].split("\n\n")[0].split("\n")
	dsn = {}
	for elem in odbc:
		info = elem.replace(' ','').split('=')
		dsn[info[0].lower()] = info[1]
	return (dsn)
def to_vertica_python_format(dsn: str):
	dsn = read_dsn(dsn)
	conn_info = {'host': dsn["servername"], 'port': 5433, 'user': dsn["uid"], 'password': dsn["pwd"], 'database': dsn["database"]}
	return (conn_info)

connection = vertica_python.connect(** to_vertica_python_format("VerticaDSN"))
cur = connection.cursor()
print(cur.execute("SELECT 1;").fetchall())
```

It will read the ODBCINI file and parse the DSN to extract the info

**Comment by sitingren** [comment]
Generally, I don't think this will not be a reasonable change.

pyodbc needs to be compliant with ODBC, so pyodbc can look at your ODBC.ini. _vertica-python_ is compliant with [DB-API](https://www.python.org/dev/peps/pep-0249/) and there's no constraint that it must complicant with ODBC as well. Adding such ability of reading the ODBCINI file will create a maintenance burden and add dependency to the content format of ODBCINI file.

I think a more reasonable improvement is adding the ability for _vertica-python_ to read connection info from environment variables. Currently there are limitations to support all connection parameters, not all parameters can be expressed as string, such as `ssl` option accepts a `ssl.SSLContext` object.

**Comment by sitingren** [comment]
Asking for @tomwall 's opinion.

**Comment by sitingren** [comment]
@oualib Minor suggestion: Rather than parsing the ODBCINI file manually with `split()`, you can easily get the content with the [configparser](https://docs.python.org/3/library/configparser.html) library.

**Comment by oualib** [comment]
Cool, this library can help for code optimization! Thanks!

If you leave the user enter his own information, he will have to enter his credentials which can lead to unwanted results. No one wants to share a screen with the credentials already prepared. The DSN is in my opinion mandatory for any ODBC cursor.

**Comment by sitingren** [comment]
@oualib Yes, but please keep in mind vertica-python is NOT an ODBC driver. We leave the security of credentials input to the user.
