### ISSUE TITLE
Allow to enable logging without file handler 

### ISSUE THREAD

**Issue by AlexandreYang** [vertica/vertica-python#340]
## The issue

It seems currently not possible to activate logger without also setting up the file handler: 

```
self.options.setdefault('log_path', DEFAULT_LOG_PATH)
```

https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/connection.py#L248

In some cases, we just want to enable the logger, but we don't want to log in a file and use the root logger handlers instead. Example [in this case](https://github.com/DataDog/integrations-core/pull/5011/files#diff-d892d1977dccc10bbbdcebf1a63dd61cR567-R569) we had to redirect the output to `os. devnull`.

## Suggestion

The change could be:

1) if `log_path` is not set, then do not set up the file handler (breaking change for those relying on `DEFAULT_LOG_PATH`)
2) if `log_path` is set to `None` then do not set up the file handler.

Option 2) is probably safer and will avoid breaking change. I can file a PR if you are ok with that.

**Comment by sitingren** [comment]
@AlexandreYang Thank you for your suggestion! Yes, I also prefer option 2).

When you are making the change, please keep in mind the logger setup logic is also used by tests: https://github.com/vertica/vertica-python/blob/master/vertica_python/tests/common/base.py#L124

**Comment by AlexandreYang** [comment]
@sitingren Thanks for the suggestion. Here is the PR that address this issue: https://github.com/vertica/vertica-python/pull/341 

Let me know if there is anything to improve.
