### ISSUE TITLE
[Question] how to use the sql argument on schema name 

### ISSUE THREAD

**Issue by Shihao-Zhong** [vertica/vertica-python#362]
Hi guys,

I am trying to use same sql with dynamic schema's and I have the following sql

SELECT * FROM :schema_name.:table_name ORDER BY RANDOM()

When I am trying to execute this sql using the following command

cur.execute(sql, {schema_name: 'abc', table_name:'def'})

And I got the following error that 

Error Code: b'4856', SQL: "SELECT * FROM 'abc'.'def'ORDER BY RANDOM();"

I believe the error reason is that the schema name can not inside the ''.

It's there anyway to solve it?

Thanks and appreciate

**Comment by sitingren** [comment]
`cursor.execute(sql, parameters)` is used for binding __SQL literals__ only. But you are trying to bind SQL [Identifiers](https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/LanguageElements/Identifiers.htm?tocpath=SQL%20Reference%20Manual%7CSQL%20Language%20Elements%7C_____2). Supporting dynamic SQL is one of TODOs in vertica-python's roadmap. So currently the solution is to
1. Bind SQL identifiers __in your program__ and generate a query string _sql_with_identifiers_. Be cautious of sql injections during binding.
2. Run `cursor.execute(sql_with_identifiers)`
