### ISSUE TITLE
Vertica Hint Support?

### ISSUE THREAD

**Issue by Jonnokc** [vertica/vertica-python#369]
Has Anyone managed to figure out how to use hints within queries?

tried today and all I get is syntax issues caused by `/*+DIRECT*/`. Query runs perfectly with the hint removed.

**Comment by sitingren** [comment]
@Jonnokc Hope the documentation is helpful:
https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/LanguageElements/Hints/direct.htm
