### ISSUE TITLE
Dict Result, instead of nested lists?

### ISSUE THREAD

**Issue by EdgeSync** [vertica/vertica-python#371]
Hi team,

Just curious if it is possible to return a Dict object, instead of the nested lists when using vertica-python.

For example in MySQLdb package, we can define the cursor class as  a DictCursor - which returns all data in Dict object.
Similarly, in Elasticsearch, all data is return as a dict by default.

Many thanks, 

Chris

**Comment by alexjikim** [comment]
from the readme:
`cur = connection.cursor('dict')
cur.execute("SELECT * FROM a_table LIMIT 2")
cur.fetchall()
# [ {'id': 1, 'value': 'something'}, {'id': 2, 'value': 'something_else'} ]
connection.close()`

**Comment by sitingren** [comment]
Closed. Reopen this issue if you have further questions, thanks!

**Comment by EdgeSync** [comment]
This is embarrassing, I read through the documentation here:
https://www.vertica.com/docs/9.1.x/HTML/python_client/index.html

But seems this is incomplete compared to the README. Now that @alexjikim pointed it out, it's very obvious. Apologies for wasting time.
