### ISSUE TITLE
any plan to make this work with Python 3 ?

### ISSUE THREAD

**Issue by xwolfgan** [vertica/vertica-python#38]
currently it is not compatible.

**Comment by BasilPH** [comment]
Any news on this? I would really appreciate it if this also worked with python 3. Otherwise this library is a joy to work with.

**Comment by alexjikim** [comment]
sorry, but we dont currently have plans to add python 3 support

**Comment by Bennyelg** [comment]
to convert this code into python 3 is a huge work and I guess they don't have time.
I'm fan of python 2 (legacy) so I have no complains.
