### ISSUE TITLE
Get the rowcount of COPY

### ISSUE THREAD

**Issue by dcordero** [vertica/vertica-python#380]
I am trying to get the number of rows imported by a COPY statement. To do so, I am following a similar approach [to the documentation describing how to get the rowcount after a SELECT or DELETE statement](https://github.com/vertica/vertica-python#rowcount-oddities)

```python
with open("/tmp/binary_file.csv", "rb") as fs:
    cursor.copy("COPY table(field1, field2) FROM STDIN DELIMITER ',' ENCLOSED BY '\"'",
                fs, buffer_size=65536)

     rowcount = cursor.fetchone()[0]
     print("Imported {} rows".format(rowcount))
```

As a result of this code I am getting the following result
```
Imported None rows
```

is there a way to get the number of imported rows by a COPY statement?

**Comment by sitingren** [comment]
@dcordero Unfortunately, `cursor.copy()` is not able to return the number of rows loaded. The good new is that we are on the way to implement COPY LOCAL protocol, so that you can run a COPY LOCAL query in `cursor.execute()` and fetch the rows loaded.

**Comment by tomwall** [comment]
COPY LOCAL (including COPY LOCAL STDIN) is available on master now should include the row count, but COPY STDIN doesn't and that's a server-side limitation the client can't really do much about. 

There is also a get_num_accepted_rows() function (https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/VerticaFunctions/GET_NUM_ACCEPTED_ROWS.htm) that might do what you want.
