### ISSUE TITLE
Vertica python failing when file has null value

### ISSUE THREAD

**Issue by PABNY** [vertica/vertica-python#383]
Hi Team

My file is having just below 2 columns
"","test"

DDL is below

create table test_null
  ( num NUMERIC(10,5) ,
    var VARCHAR(50)
  ) 

Code is below

newlist=["num","var"]
delcmd="DELETE FROM test_null"
copycmd="""Copy test_null ({}) FROM stdin DELIMITER ',' NULL '' ENCLOSED BY '\"' ESCAPE AS '\\' ABORT ON ERROR""".format(','.join(newlist))
with open(final_file_name, "rb") as f:
        my_file = f.read().decode('utf-8')
        cur = vertica_conn.cursor()
        cur.execute(delcmd)
        cur.copy(copycmd, my_file)
Getting error
COPY: Input record 1 has been rejected (Invalid numeric format '' for column 1 (num))

have tried many combination as 
NULL as ''
etc etc but all have same error

If I change the file to have value then it works but my column can have null

"0","test"

Please help

Thanks

**Comment by sitingren** [comment]
You don't need to enclosed every column value with `"`. `ENCLOSED BY` is used for allowing **delimiter characters** to be embedded in string values. So for your example data, you can express as `,test` or `,"test"`.

**Comment by sitingren** [comment]
Closed. Reopen this issue if you have further questions. Thanks.
