### ISSUE TITLE
When is the expected end of support for python 2.7?

### ISSUE THREAD

**Issue by darwinyip** [vertica/vertica-python#390]
Just throwing this out. Any considerations on when to drop support for python 2.7?

**Comment by tomwall** [comment]
Python 2.7 support will probably remain for a while, but you shouldn't use that as an excuse to avoid upgrading :)

Pypi download stats (https://pypistats.org/packages/vertica-python) show it is still heavily used, and for now at least, there isn't much of a cost to keeping it going. 2.7 usage does seem to be declining slowly, and we'll probably see that accelerate as more of Vertica's user base upgrades to RHEL8 and other platforms where 2.7 is not the default. 

Over time as the world moves on it will likely grow harder to support, and as it does we'll have to consider the tradeoffs of keeping it around. It would be nice to take advantage of newer features like type annotations, but not at the expense of 25% of the library's usage. If its 5% in a year maybe then it is more feasible, but even then we'd want to do it carefully with input from the community.

vertica-python is backwards & forwards compatible with the Vertica server. It works back to 7.1 and will continue working in future Vertica releases. So if/when 2.7 is dropped, the existing releases will still work if you are stuck on 2.7. You may not get access to the latest features, but that's an inevitable cost of remaining on an unsupported platform.
