### ISSUE TITLE
Examples not working .. need help with INSERT INTO

### ISSUE THREAD

**Issue by jakane** [vertica/vertica-python#393]
If this is not the correct place, please redirect me ...

Extracting from an example in `README.md`, I have the following

```python
import sys
import vertica_python

conn_info = { ... }

print(f"Python version: {sys.version}")
print(f"vertica_python.__version__: {vertica_python.__version__!r}")

with vertica_python.connect(**conn_info) as connection:
    cur = connection.cursor()
    cur.execute("SELECT VERSION()")
    print(f"Vertica Version: {cur.fetchall()!r}")
    cur.execute("DROP TABLE IF EXISTS tbl")
    cur.execute("CREATE TABLE tbl (a INT, b VARCHAR)")
    cur.execute("INSERT INTO tbl VALUES (?, ?)", [1, 'aa'])
    cur.execute("INSERT INTO tbl VALUES (?, ?)", [2, 'bb'])
    cur.executemany("INSERT INTO tbl VALUES (?, ?)", [(3, 'foo'), (4, 'xx'), (5, 'bar')])
    cur.execute("COMMIT")

    cur.execute("SELECT * FROM tbl WHERE a>=? AND a<=? ORDER BY a", (2,4))
    print(cur.fetchall())
```
I get the following output:

```bash
$ pipenv run python check_vertica_01.py 
Loading .env environment variables…
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
vertica_python.__version__: '0.11.0'
Vertica Version: [['Vertica Analytic Database v9.3.1-2']]
Traceback (most recent call last):
  File "check_vertica_01.py", line 27, in <module>
    cur.execute("INSERT INTO tbl VALUES (?, ?)", [1, 'aa'])
  File "/home/jkane/wrk/netflow_vertica/.venv/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 221, in execute
    operation = self.format_operation_with_parameters(operation, parameters)
  File "/home/jkane/wrk/netflow_vertica/.venv/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 578, in format_operation_with_parameters
    operation = operation % tuple(tlist)
TypeError: not all arguments converted during string formatting
```

**Comment by sitingren** [comment]
I think the problem is you are using the wrong placeholder `?` in the sql. Parameter placeholder `?` is used when 'use_prepared_statements' option is True, otherwise you should use placeholder `%s` when 'use_prepared_statements' is False (by default). Please read up to README.md.

**Comment by jakane** [comment]
Thanks for the reply.

I did pull that example from `README.md`, but did not notice (nor was it called out) that apparently `cursor().executemany()` **must** be done with `use_prepared_statements == True`. 

There are no comments about `cursor().executemany()`, it appears in only 3 files in the codebase and only once in `README.md`. Reading the code for `def executemany()` in `cursor.py` kind of *implies* that it would work with either prepared statements or not prepared statements. 

https://github.com/vertica/vertica-python/blob/b45d599d04260e170c49e0928e37605882d35cad/vertica_python/vertica/cursor.py#L241

Here is what triggers this:
https://github.com/vertica/vertica-python/blob/b45d599d04260e170c49e0928e37605882d35cad/vertica_python/vertica/cursor.py#L254-L279

I *think* https://github.com/vertica/vertica-python/blob/b45d599d04260e170c49e0928e37605882d35cad/vertica_python/vertica/cursor.py#L255 is ***not*** recognizing this as an `INSERT INTO` statement.

I obviously can work-around my issue by using prepared statements. Can we get an update to the documentation, and maybe a `BUG` raised against the pattern? https://github.com/vertica/vertica-python/blob/b45d599d04260e170c49e0928e37605882d35cad/vertica_python/vertica/cursor.py#L125-L128

I think the issue is the clause that is on line 127, namely https://github.com/vertica/vertica-python/blob/b45d599d04260e170c49e0928e37605882d35cad/vertica_python/vertica/cursor.py#L127

That does not appear to be optional. So naming the columns would be required:

```python
$ ipython
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import re 
   ...:  
   ...: RE_NAME_BASE = u"[0-9a-zA-Z_][\\w\\d\\$_]*" 
   ...: RE_NAME = u'(("{0}")|({0}))'.format(RE_NAME_BASE) 
   ...: RE_BASIC_INSERT_STAT = ( 
   ...:     u"INSERT\\s+INTO\\s+(?P<target>({0}\\.)?{0})" 
   ...:     u"\\s*\\(\\s*(?P<variables>{0}(\\s*,\\s*{0})*)\\s*\\)" 
   ...:     u"\\s+VALUES\\s*\\(\\s*(?P<values>(.|\\s)*)\\s*\\)").format(RE_NAME) 
   ...:  
   ...: _insert_statement = re.compile(RE_BASIC_INSERT_STAT, re.U | re.I) 
   ...:  
   ...: # Will Pass 
   ...: assert _insert_statement.match("INSERT INTO tbl (col1, col2, col3) VALUES (?, ?, ?)") 
   ...:  
   ...: # Will Fail 
   ...: assert _insert_statement.match("INSERT INTO tbl VALUES (?, ?, ?)") 
   ...:                           
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-c07f6448dd6f> in <module>
     14 
     15 # Will Fail
---> 16 assert _insert_statement.match("INSERT INTO tbl VALUES (?, ?, ?)")

AssertionError: 
```

Changing line 127 to be:

```python
u"(\\s*\\(\\s*(?P<variables>{0}(\\s*,\\s*{0})*)\\s*\\))?"
```

Results in:

```python
In [4]: RE_BASIC_INSERT_STAT = ( 
   ...:     u"INSERT\\s+INTO\\s+(?P<target>({0}\\.)?{0})" 
   ...:     u"\\s*(\\(\\s*(?P<variables>{0}(\\s*,\\s*{0})*)\\s*\\))?" 
   ...:     u"\\s+VALUES\\s*\\(\\s*(?P<values>(.|\\s)*)\\s*\\)").format(RE_NAME) 
   ...:  
   ...: _fixed_insert_statement = re.compile(RE_BASIC_INSERT_STAT, re.U | re.I) 
   ...:  
   ...: # Will Pass 
   ...: assert _fixed_insert_statement.match("INSERT INTO tbl (col1, col2, col3) VALUES (?, ?, ?)") 
   ...:  
   ...: # Will now Pass 
   ...: assert _fixed_insert_statement.match("INSERT INTO tbl VALUES (?, ?, ?)") 
   ...:  
   ...:                           

In [5]:
```

I have done no other testing than this, so I do not proffer this as a fix, but I added a grouping around the whole line and made it optional.

Thanks

**Comment by sitingren** [comment]
The usage of `cursor.executemany(sql, param_value_sets[,use_prepared_statements])` can be described as
(1) When use_prepared_statements is True, sql is a single statement with parameter placeholder `?`, the query pattern is not limited to INSERT INTO.
(2) When use_prepared_statements is False, sql uses placeholder `%s` or `:pname`, and the query must be a INSERT INTO command. Internally, the query would be converted to a COPY statement for execution. The query pattern is defined by
https://github.com/vertica/vertica-python/blob/b45d599d04260e170c49e0928e37605882d35cad/vertica_python/vertica/cursor.py#L125-L128
And yes, this regex is not perfect. So naming the columns would be required. You are welcome to contribute a fix to meet your needs.

The usage above also applies to `cursor.execute()` except there are no INSERT INTO pattern restriction for (2).
