### ISSUE TITLE
CommandComplete not handled gracefully

### ISSUE THREAD

**Issue by 2ps** [vertica/vertica-python#394]
After upgrading from 0.10.3, `copy` stopped working because it did not handle `CommandComplete`.  Instead we received the following exception:

```
Received unexpected message type: CommandComplete. Expected type: CopyInResponse
```

**Comment by sitingren** [comment]
@2ps The latest version is 0.11.0. If you see this issue in the latest version, please provide a reproducer program. Thank you!

**Comment by sitingren** [comment]
Reopen this issue if you have further questions, thanks.
