### ISSUE TITLE
Using socket.recv() with small values is expensive

### ISSUE THREAD

**Issue by alippai** [vertica/vertica-python#397]
Using the file-like object with `read(1)` is better if you set up buffering eg. using `socket.makefile(mode='rb', buffering=1024*1024)`. Avoiding frequent system calls caused by recv() the data row fetching can double the throughput (on large datasets).

**Comment by sitingren** [comment]
@alippai Thanks for your suggestions! Please feel free to make a pull request for this improvement.

**Comment by alonme** [comment]
closed by #441.
