### ISSUE TITLE
Missing dependency binaries for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [vertica/vertica-python#408]
**Problem description:**
I am trying to use vertica-python on ARM64 but aarch64 binaries similar to https://vertica-community-edition-for-testing.s3.amazonaws.com/XCz9cp7m/vertica-10.0.1-0.x86_64.RHEL6.rpm is missing. So, I am not able to build the docker image for the arm64 architecture.

**Expected behavior:**
All the required binaries should be available for aarch64 architecture. 

Please let me know if I can help you in adding these binary support for aarch64.

**Comment by sitingren** [comment]
Hi @odidev, Do you want to run vertica-python **client** or the Vertica **server** on ARM64? They can run on different machines.

As mentioned in [Vertica server documentation](https://www.vertica.com/docs/10.0.x/HTML/Content/Authoring/SupportedPlatforms/MCandServer.htm?tocpath=Vertica%2010.0.x%20Supported%20Platforms%7C_____1), the Vertica server only supports x86_x64 architecture. So you **cannot** install Vertica server on the ARM64 architecture. And we never try running vertica-python client on ARM64, not sure if it is possible.

If your question is referring to the Github Actions CI tests this repo runs, the docker image consuming the rpm file is used for setting up a single-node Vertica server that a client can connect to. And the vertica-python client (also the `docker` command) is running on the environment provided by Github Actions. If you want to run vertica-python on ARM64, you have to setup a GitHub Action that executes commands on ARM64. But the docker image for Vertica server would always build with x86_x64.

**Comment by odidev** [comment]
@sitingren thanks for your reply. I was thinking to setup vertica client and server on aarch64 machine. Now, with your explanation, I am aware that vertica server doesn't support aarch64. Could you please let me know if you have any plans for adding aarch64 support for vertica server?

**Comment by sitingren** [comment]
@odidev AFAIK, there is no plan to add aarch64 support for vertica server in the near future. Since this channel aims to talk about client issues, please talk to your support contact with server issues. Thanks!
