### ISSUE TITLE
need Keep-Alive...queries killed at 60 minutes?

### ISSUE THREAD

**Issue by mattberns** [vertica/vertica-python#410]
We are using `vertica-python` via `dbt-vertica` and we're finding that our log running queries are getting killed at 3600 seconds. We are told that we need to implement `Keep-Alive` since there are no packets being transacted for > 60 minutes. TCP connections that are idle are being killed at 60 minutes.

Is this a setting we can enable here? it appears that the way this is being done in some tools is to submit a query every N seconds over an open connection like `SELECT 1`. Does the driver support this?

**Comment by sitingren** [comment]
Hi @mattberns 
There are related discussion at #205. 

Basically, vertica-python provides `connection_timeout` as a connection parameter to control socket operations timeout (see README), queries can be affected by this. Please note that dbt-vertica is a third-party library that we don't support. If you want to set `connection_timeout`, you may need to change your libraries source code. The 3600 seconds comes from `dbt-vertica`:
https://github.com/mpcarter/dbt-vertica/search?q=timeout&type=

**Comment by mattberns** [comment]
@sitingren Thanks for this. Going to close this one. It turns out there is a `timeout` parameter over at `dbt-vertica` and this was set to `connection-timeout` in our repo which was misleading us ( because this setting passes through to `connection-timeout` This does seem to differ from the broken pipe issue which a colleague was experiencing less than the setting value, which we believe is due to a misconfiguration of the server.
