### ISSUE TITLE
Disconnected at 7200 seconds

### ISSUE THREAD

**Issue by mattberns** [vertica/vertica-python#413]
We are currently using vertica-python to connect from a windows machine to vertica (hosted on linux). We are consistently getting our long running queries disconnected at 7200 seconds. We see:

https://github.com/vertica/vertica-python/blob/74d426fae75b0fe221e65a1ed20eff6889970ce9/vertica_python/vertica/connection.py#L451

It looks like the keepalive is set...what could be causing this? 7200 I know is the keepalive time.

Is this also going to work for windows? Do we also need https://docs.python.org/3/library/socket.html#socket.socket.ioctl with SIO_KEEPALIVE_VALS for socket to remain open?

**Comment by sitingren** [comment]
vertica-python provides `connection_timeout` as a connection parameter to control socket operations timeout (see README), queries can be affected by this. Please check if you have set `connection_timeout` first.

**Comment by sitingren** [comment]
Close this issue because it has not had recent activity.
