### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [vertica/vertica-python#425]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/vertica_python/vertica/cursor.py b/vertica_python/vertica/cursor.py
index 68e6f3f..f818b90 100644
--- a/vertica_python/vertica/cursor.py
+++ b/vertica_python/vertica/cursor.py
@@ -117,7 +117,7 @@ file_type = tuple(
 )
 if six.PY2:
     # noinspection PyUnresolvedReferences
-    file_type = file_type + (file,)
+    file_type += (file,)
 
 
 RE_NAME_BASE = u"[0-9a-zA-Z_][\\w\\d\\$_]*"
@@ -573,7 +573,7 @@ class Cursor(object):
                 value = self.object_to_string(param, is_copy_data)
                 tlist.append(value)
 
-            operation = operation % tuple(tlist)
+            operation %= tuple(tlist)
         else:
             raise TypeError("Argument 'parameters' must be dict or tuple/list")
 
```

**Comment by sitingren** [comment]
@elfring What "source code analysis tools" are you referring to?

**Comment by elfring** [comment]
:thought_balloon: I suggest to [take another look at known analysis tools](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#Python "Tools for static code analysis").
I found the shown update candidates with the help of a tiny Perl command (which I constructed for this transformation pattern).
