### ISSUE TITLE
A query with multiple statements should return the results of the last statement not the first one

### ISSUE THREAD

**Issue by edoven** [vertica/vertica-python#426]
Hey, I hope this has not been discussed before. :) 
Often multiple statements are used to build temp tables, that are then read in the final statement (sorry I don't have any data  to support this, just personal experience).
Other tools (e.g. DBVisualizer) returns the results of the last statement.
Vertica-python returns the first statement.
```
SELECT 1;  --> this is returned
SELECT 2;
```
This is a little bit counterintuitive and makes using temp tables a little bit more complex.

**Comment by sitingren** [comment]
Hello @edoven 

First of all, DBVisualizer is not only returns the results of the last statement. It actually fetches the result set of each statement and displays them as different tabs, but the last statement's results is the selected tab.

So interpreting DBVisualizer's process into vertica-python function calls, it is `Cursor.execute(...multi-statements...)`->`Cursor.fetchall()` and **save** the first result set -> `Cursor.nextset()` -> `Cursor.fetchall()` and **save** the second result set.

vertica-python implements a [DBAPI-compliant](https://www.python.org/dev/peps/pep-0249/#nextset) interface. If vertica-python returns the last statement directly, it is not able to retrieve previous result sets with available APIs.

I recommend you create a shortcut function to execute and return the results of the last statement.

**Comment by edoven** [comment]
@sitingren, that makes sense. Thanks for the help!
