### ISSUE TITLE
Adding all the possible connection parameters in the readme

### ISSUE THREAD

**Issue by oualib** [vertica/vertica-python#451]
I find it really hard to find all the options provided by the connector. We have at the beginning of the README, this sentence:

📜 The basic vertica-python usage is common to all the database adapters implementing the [DB-API v2.0](https://www.python.org/dev/peps/pep-0249/) protocol.

But still it is hard to understand the options we can add in the conn_info.

**Comment by sitingren** [comment]
@oualib README is updated. Let me know if you have more questions.

**Comment by oualib** [comment]
Excellent, thank you so much! It is really helpful
