### ISSUE TITLE
How safe is it to use datatypes module?

### ISSUE THREAD

**Issue by vladpy8** [vertica/vertica-python#455]
How safe is it to use [datatypes](https://github.com/vertica/vertica-python/blob/master/vertica_python/datatypes.py) module? It lacks documentation. At least I wasn't able to find one. Except too general to be usefull in my case PEP 249 

Is it safe to look into source code and assume that VerticaType and other useful definitions won't change somehow in future? Usually documentation is quite "reliable" indicator that some functionality is supported and thus preserved and changed in accordance to version control

P.S. My case is quite specific and is related to getting data types from vertica as precisely as possible. So very general PEP 249 definitions like NUMERIC - aren't of much use to me. It would be much more neat to have reliable access to VerticaType.INT8, VerticaType.FLOAT8, etc.

Thanks :)

**Comment by sitingren** [comment]
Hi @vladpy8  It is unlikely the existing types & their definitions to be changed, but there will be new data types added in the future.

**Comment by sitingren** [comment]
Closed. Re-open if you have further questions. Thanks.
