### ISSUE TITLE
cursor.copy silent failure

### ISSUE THREAD

**Issue by eugene-rozman** [vertica/vertica-python#456]
When executing cursor.copy(copyStmt, input) with the malformed 'input' - e.g. containing extra comma-separated fields, the statement fails to write to the DB while not raising any error in Python. Suggest that this either changed to raising an error, or at least an option given to either ignore or raise. 
Otherwise, there's no way to guarantee copy or see that it failed and why, short of writing additional code.

**Comment by sitingren** [comment]
@eugene-rozman This is not controlled by python client. Can you try to add `ABORT ON ERROR` to the end of `copyStmt` sql? E.g. "`COPY tbl (a, b) FROM STDIN DELIMITER ',' ENFORCELENGTH ABORT ON ERROR`". Please see Vertica documentation for COPY syntax about error handling.

**Comment by sitingren** [comment]
Closed. Reopen if you have further questions.
