### ISSUE TITLE
NotSupportedError: Dates Before Christ are not supported. Got: 0001-01-01 BC

### ISSUE THREAD

**Issue by Prithwee** [vertica/vertica-python#462]
![image](https://user-images.githubusercontent.com/30373414/180139924-fe351834-0d31-4966-827b-76947794e156.png)

Though am using the cur.disable_sqldata_converter = True  , am still getting the error as "NotSupportedError: Dates Before Christ are not supported. Got: 0001-01-01 BC"

**Comment by sitingren** [comment]
@Prithwee Are you using the latest version of vertica-python?

**Comment by Prithwee** [comment]
i was using  version 1.0.1  , then switched to  1.1.1 and it worked. Thanks!
