### ISSUE TITLE
Poor performance reading in large number of rows 

### ISSUE THREAD

**Issue by mwlon** [vertica/vertica-python#470]
I've been comparing vertica-python vs pyodbc and found that in some cases, especially for large narrow queries like
`pd.read_sql("select int_col from my_table limit 1000000")`, vertica-python is 4x slower. I think this suggests a big performance win should be possible.

vertica-python: 1.1.1
pyodbc: 4.0.32
pandas: 1.3.5
python: 3.8.8

**Comment by sitingren** [comment]
Hi @mwlon Have you read https://github.com/vertica/vertica-python#frequently-asked-questions-speech_balloon and try vertica-python with PyPy?

**Comment by mwlon** [comment]
Oops, I hadn't noticed that section - feel free to close. I did some profiling and found the slowness came about half from buffering in data, half from deserialization, both mainly due to C++/Python discrepancy.
