### ISSUE TITLE
Error Position

### ISSUE THREAD

**Issue by akariasmorum** [vertica/vertica-python#472]
Hello! Some VerticaErrors contain Position (in this case Position: 9 )
`cur.execute("select *.a from existing_table;")`
`VerticaSyntaxError: Severity: ERROR, Message: Syntax error at or near ".", Sqlstate: 42601, Position: 9, Routine: base_yyerror, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Parser/scan.l, Line: 1052, Error Code: 4856, SQL: 'select *.a from existing_table;'`
and some Errors don't:
`cur.execute("select some_column from existing_table;")`
`MissingColumn: Severity: ERROR, Message: Column "some_column" does not exist, Sqlstate: 42703, Routine: transformSQLColumnRef, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Optimizer/OptUtil/ExprUtil.cpp, Line: 7256, Error Code: 2624, SQL: 'select some_column from existing_table;'`
Is it VerticaPython's or underlying driver's issue?

**Comment by sitingren** [comment]
Position info is returned by the server. Some errors just don't have that piece of info.
