### ISSUE TITLE
New feature request - add rpm build for vertica-python

### ISSUE THREAD

**Issue by scherepanov** [vertica/vertica-python#473]
Would be very nice if you will add all needed to do rpm build for vertica-python.

In ideal world, it would be some script in vertica-python repo, I will run it, and it will create me RPM.

All rpm I can find is v 0.9.3, and it is quite old.

May be you already have rpm build in repo, and I am missing it???

Thank you

**Comment by sitingren** [comment]
So far we only maintain the Wheel distribution on [PyPI](https://pypi.org/project/vertica-python) (as many other python packages do). 
Where do you find the v0.9.3 rpm? I guess you can probably use a tool to convert a PyPI package to an RPM SPECFILE such as this [pyp2rpm](https://pypi.org/project/pyp2rpm/).

**Comment by scherepanov** [comment]
I can see vertica-python is installed through rpm, and I thought it is a correct way of installing it:

$rpm -qa|grep vertica-python
python-vertica-python-0.7.3-1.noarch

This is top result in Goolge search for vertica-python rpm, it has few versions:
https://src.fedoraproject.org/rpms/vertica-python

I still think it would be very nice to have script that will create RPM out of repo.

**Comment by sitingren** [comment]
It is really rare for open source python projects to provide RPM distributions. Installing from PyPI with _pip_ is the preferred way for most open source python projects. 
Providing a RPM distribution is not as easy as just upload a script without any testings and future updates. We don't have resource to make huge efforts on maintenance.
