### ISSUE TITLE
Automated tests via Travis (or some other CI service)

### ISSUE THREAD

**Issue by nchammas** [vertica/vertica-python#95]
Are the maintainers interested in automating the project's tests via a CI service like Travis? We can use a dockerized instance of Vertica to enable this.

It'll let us test PRs and hopefully move more quickly on refactoring the codebase or adding stuff as the need arises.

**Comment by nicktrav** [comment]
+1

**Comment by nchammas** [comment]
I suppose this idea first requires that Vertica be publicly accessible so that you can download and set it up as part of your automated tests. As far as I know, there are no publicly accessible versions of Vertica as you need an account setup on their site and you need to click through some license agreement every time you download something.

I've [asked on the Vertica community forum](https://community.dev.hpe.com/t5/Vertica-Forum/Public-Vertica-download-for-continuous-integration-tests/m-p/236175) about a public download but haven't heard back.

**Comment by sevagh** [comment]
Look at how this repo does it: https://github.com/wvanbergen/vertica/blob/master/.travis.yml

`sudo wget -nv https://s3.amazonaws.com/circle-support-bucket/vertica_7.0.1-0_amd64.deb`

Personally I use https://hub.docker.com/r/sumitchawla/vertica/ for tests. They are both decent options but the versions are quite old.

**Comment by pachewise** [comment]
bumping this: I've had some success testing code at work with CircleCI 2.0 and a vertica docker container from: https://github.com/jbfavre/docker-vertica. We _might_ be able to get it working on travis (though it would be somewhat out of my depth), if that's the preferred CI service. Regardless, having some tests run whenever a PR is submitted would be helpful

**Comment by tomwall** [comment]
Thanks for everyone's help & interest. We've now got basic CI up and running via https://github.com/vertica/vertica-python/pull/216. 

It is normally against Vertica's user agreement to host public downloads, but we've gotten special exception to do so for this project. You're welcome to use the URL referenced in the CI script on https://travis-ci.com/vertica/vertica-python/ for your own testing, but the URL may change as new Vertica releases ship. 

This is good enough for now. Over time we hope to make a more robust CI/dockerized testing solution that tests across a variety of Vertica versions and can be reused for other projects, but there is still more to learn and be done before that will be possible.
